# Generated by Django 3.2.6 on 2021-08-08 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('ordered_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
