# Generated by Django 3.2.7 on 2021-09-17 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('ordered_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
